# Generated by Django 2.2.3 on 2019-09-15 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
    ]
