# Generated by Django 2.2.3 on 2019-09-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('position', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('record', models.CharField(max_length=10)),
                ('points', models.IntegerField()),
                ('rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('threes', models.IntegerField()),
                ('freethrows', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
