# Generated by Django 2.2.3 on 2019-09-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190916_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='f_name',
            new_name='first_name',
        ),
    ]
